#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

# OldHospital-only student-objective ablation.
#
# This keeps the LA_update29 clean data boundary:
#   real train RGB only, no synthetic, no artifact/mask branch, no teacher gate.
# The only intentional change is the student objective:
#   pseudo-query reliability soft loss + stage-aware direct component weights.

RUN_STAMP=${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}
LOG_ROOT=${LOG_ROOT:-/mnt/pool/sqy/stdloc_la_oldhospital_objective_logs_${RUN_STAMP}}
OUT_ROOT=${OUT_ROOT:-/mnt/pool/sqy/stdloc_la_oldhospital_objective_${RUN_STAMP}}
GPU=${GPU:-0}
TRAIN_SEED=${TRAIN_SEED:-411}
LA_ADAPT_STEPS=${LA_ADAPT_STEPS:-500}
LANDMARK_NUM=${LANDMARK_NUM:-8192}

mkdir -p "$LOG_ROOT"

export SCENES=OldHospital
export GPU
export OUT_ROOT
export TRAIN_SEED
export LA_ADAPT_STEPS
export LA_BOOTSTRAP_LANDMARK_NUM="$LANDMARK_NUM"
export LA_DETECTOR_LANDMARK_NUM="$LANDMARK_NUM"
export LA_DETECTOR_ITERS="${LA_DETECTOR_ITERS:-$LA_ADAPT_STEPS}"

export LA_ENABLE_SYNTHETIC=0
export SYNTHETIC_COUNT=0
export SYNTHETIC_CANDIDATE_MULTIPLIER=1
export TEACHER_CACHE_SOURCES=train_rgb
export TEACHER_CACHE_SPARSE_VALID_MASK=0
export RUN_PSEUDO_QUERY_GATE=0
export RUN_PSEUDO_QUERY_SELECT=0
export PSEUDO_QUERY_SOURCES=train_rgb
export PSEUDO_QUERY_MAX_SYNTHETIC=0
export PSEUDO_QUERY_SELECT_MAX_SYNTHETIC=0
export PSEUDO_QUERY_EXCLUDE_SPARSE_FAILURE_STAGES=0
export PSEUDO_QUERY_FILTER_TEACHER_CACHE=0
export PSEUDO_QUERY_REQUIRE_TEACHER_CACHE=1
export PSEUDO_QUERY_ENABLE_TEACHER_GATE=0
export PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT=0
export LA_DIRECT_DEPTH_CHECK=0

export PSEUDO_QUERY_RELIABILITY_MODE=soft
export PSEUDO_QUERY_RELIABILITY_LOSS_MODE=soft
export PSEUDO_QUERY_STAGE_OBJECTIVE_MODE=direct
export PSEUDO_QUERY_STAGE_STATS_POLICY=${PSEUDO_QUERY_STAGE_STATS_POLICY:-soft}
export PSEUDO_QUERY_RELIABILITY_MIN_WEIGHT=${PSEUDO_QUERY_RELIABILITY_MIN_WEIGHT:-0.20}
export PSEUDO_QUERY_RELIABILITY_REAL_MIN_WEIGHT=${PSEUDO_QUERY_RELIABILITY_REAL_MIN_WEIGHT:-0.45}
export PSEUDO_QUERY_RELIABILITY_MEMORY_MIN_WEIGHT=${PSEUDO_QUERY_RELIABILITY_MEMORY_MIN_WEIGHT:-0.80}
export PSEUDO_QUERY_RELIABILITY_STATS_MIN_WEIGHT=${PSEUDO_QUERY_RELIABILITY_STATS_MIN_WEIGHT:-0.0}
export PSEUDO_QUERY_RELIABILITY_ERROR_SCALE=${PSEUDO_QUERY_RELIABILITY_ERROR_SCALE:-1.5}
export PSEUDO_QUERY_RELIABILITY_INLIER_POWER=${PSEUDO_QUERY_RELIABILITY_INLIER_POWER:-0.75}
export PSEUDO_QUERY_RELIABILITY_TEACHER_OK_WEIGHT=${PSEUDO_QUERY_RELIABILITY_TEACHER_OK_WEIGHT:-1.0}
export PSEUDO_QUERY_RELIABILITY_DENSE_IMPROVES_WEIGHT=${PSEUDO_QUERY_RELIABILITY_DENSE_IMPROVES_WEIGHT:-0.95}
export PSEUDO_QUERY_RELIABILITY_MIXED_WEIGHT=${PSEUDO_QUERY_RELIABILITY_MIXED_WEIGHT:-0.60}
export PSEUDO_QUERY_RELIABILITY_DENSE_RESCUES_WEIGHT=${PSEUDO_QUERY_RELIABILITY_DENSE_RESCUES_WEIGHT:-0.70}
export PSEUDO_QUERY_RELIABILITY_SPARSE_FAILURE_WEIGHT=${PSEUDO_QUERY_RELIABILITY_SPARSE_FAILURE_WEIGHT:-0.25}
export PSEUDO_QUERY_RELIABILITY_DENSE_REGRESSION_WEIGHT=${PSEUDO_QUERY_RELIABILITY_DENSE_REGRESSION_WEIGHT:-0.25}
export PSEUDO_QUERY_RELIABILITY_UNKNOWN_WEIGHT=${PSEUDO_QUERY_RELIABILITY_UNKNOWN_WEIGHT:-0.50}

export LA_TRAIN_MODE=scratch
export RUN_PSEUDO_QUERY_MANIFEST=${RUN_PSEUDO_QUERY_MANIFEST:-1}
export RUN_TEACHER_CACHE=${RUN_TEACHER_CACHE:-1}
export RUN_TEACHER_CACHE_AUDIT=${RUN_TEACHER_CACHE_AUDIT:-1}
export RUN_TRAIN=${RUN_TRAIN:-1}
export RUN_EVAL=${RUN_EVAL:-1}
export RUN_LA_FRONTEND_REFRESH=${RUN_LA_FRONTEND_REFRESH:-1}
export FORCE_LA_FRONTEND_REFRESH=${FORCE_LA_FRONTEND_REFRESH:-0}

set -o pipefail
bash "$SCRIPT_DIR/run_la_pseudo_query_pipeline.sh" 2>&1 | tee "$LOG_ROOT/oldhospital_objective_${LANDMARK_NUM}_${LA_ADAPT_STEPS}_seed${TRAIN_SEED}.log"
