#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

# Refactored LA-STDLoc mainline:
#   all Cambridge train RGB pseudo-queries
#   MAtCha-rendered spatial-offset synthetic RGB pseudo-queries
#   no hard teacher gate, no selector ranking, no teacher-stage loss weighting
#   full sparse+dense STDLoc teacher cache as diagnostics and pose supervision cache
#   no-reference support guidance for synthetic sparse/dense teacher localization
#   no-reference region weighting for synthetic student direct localization loss

SCENES=${SCENES:-ShopFacade OldHospital}
SYNTHETIC_COUNT=${SYNTHETIC_COUNT:-256}
LA_ADAPT_STEPS=${LA_ADAPT_STEPS:-2000}
TRAIN_SEED=${TRAIN_SEED:-0}
LA_LANDMARK_NUM=${LA_LANDMARK_NUM:-8192}

export SCENES
export SYNTHETIC_COUNT
export LA_ADAPT_STEPS
export TRAIN_SEED

export LA_ENABLE_SYNTHETIC=1
export SYNTHETIC_CANDIDATE_MULTIPLIER=1
export SYNTHETIC_QUALITY_GATE=0
export REPAIR_SYNTHETIC_ARTIFACTS=0
export RENDER_SYNTHETIC_BACKEND=matcha
export PSEUDO_QUERY_POSE_SAMPLER=spatial_offset
export SYNTHETIC_SPATIAL_MIN_OFFSET_RATIO=${SYNTHETIC_SPATIAL_MIN_OFFSET_RATIO:-1.0}
export SYNTHETIC_SPATIAL_MAX_OFFSET_RATIO=${SYNTHETIC_SPATIAL_MAX_OFFSET_RATIO:-3.0}
export SYNTHETIC_SPATIAL_YAW_DEG=${SYNTHETIC_SPATIAL_YAW_DEG:-20.0}
export SYNTHETIC_SPATIAL_HEIGHT_OFFSET_RATIO=${SYNTHETIC_SPATIAL_HEIGHT_OFFSET_RATIO:-0.15}

export TEACHER_CACHE_SOURCES=train_rgb,synthetic_rgb
export TEACHER_CACHE_MAX=0
export TEACHER_CACHE_SPARSE_VALID_MASK=1
export TEACHER_CACHE_SPARSE_VALID_MASK_MODE=support_mask_score
export TEACHER_CACHE_SPARSE_VALID_MASK_SOURCES=synthetic_rgb
export TEACHER_CACHE_SPARSE_VALID_MASK_MIN_FRACTION=${TEACHER_CACHE_SPARSE_VALID_MASK_MIN_FRACTION:-0.5}
export TEACHER_CACHE_SPARSE_VALID_MASK_CANDIDATE_MULTIPLIER=${TEACHER_CACHE_SPARSE_VALID_MASK_CANDIDATE_MULTIPLIER:-2.0}
export TEACHER_CACHE_SPARSE_SUPPORT_SCORE_WEIGHT=${TEACHER_CACHE_SPARSE_SUPPORT_SCORE_WEIGHT:-0.5}
export TEACHER_CACHE_SPARSE_SUPPORT_SCORE_MIN_MULTIPLIER=${TEACHER_CACHE_SPARSE_SUPPORT_SCORE_MIN_MULTIPLIER:-0.75}

export RUN_PSEUDO_QUERY_GATE=0
export RUN_PSEUDO_QUERY_SELECT=0
export PSEUDO_QUERY_SOURCES=train_rgb,synthetic_rgb
export PSEUDO_QUERY_MAX_SYNTHETIC=0
export PSEUDO_QUERY_SELECT_MAX_SYNTHETIC=0
export PSEUDO_QUERY_REAL_WEIGHT=${PSEUDO_QUERY_REAL_WEIGHT:-2.0}
export PSEUDO_QUERY_SYNTHETIC_WEIGHT=${PSEUDO_QUERY_SYNTHETIC_WEIGHT:-1.0}
export PSEUDO_QUERY_SAMPLING_MODE=${PSEUDO_QUERY_SAMPLING_MODE:-record_proportional}
export PSEUDO_QUERY_RELIABILITY_MODE=none
export PSEUDO_QUERY_RELIABILITY_LOSS_MODE=none
export PSEUDO_QUERY_STAGE_OBJECTIVE_MODE=none
export PSEUDO_QUERY_EXCLUDE_SPARSE_FAILURE_STAGES=0
export PSEUDO_QUERY_FILTER_TEACHER_CACHE=0
export PSEUDO_QUERY_REQUIRE_TEACHER_CACHE=1
export PSEUDO_QUERY_ENABLE_TEACHER_GATE=0
export PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT=1
export PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT_SOURCES=synthetic_rgb
export PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT_MIN=${PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT_MIN:-0.25}
export PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT_SUPPORT_POWER=${PSEUDO_QUERY_NO_REFERENCE_REGION_WEIGHT_SUPPORT_POWER:-1.0}

export LA_DIRECT_DEPTH_CHECK=0
export LA_TRAIN_MODE=scratch
export RUN_PSEUDO_QUERY_MANIFEST=${RUN_PSEUDO_QUERY_MANIFEST:-1}
export RUN_TEACHER_CACHE=1
export RUN_TEACHER_CACHE_AUDIT=${RUN_TEACHER_CACHE_AUDIT:-1}
export RUN_TRAIN=1
export RUN_EVAL=1
export RUN_LA_FRONTEND_REFRESH=1
export FORCE_LA_FRONTEND_REFRESH=${FORCE_LA_FRONTEND_REFRESH:-0}

export LA_BOOTSTRAP_LANDMARK_NUM="$LA_LANDMARK_NUM"
export LA_DETECTOR_LANDMARK_NUM="$LA_LANDMARK_NUM"
export LA_DETECTOR_ITERS=${LA_DETECTOR_ITERS:-${LA_ADAPT_STEPS}}
if [[ -z "${LA_DETECTOR_MIN_LOC_OBSERVATIONS+x}" ]]; then
  if (( LA_ADAPT_STEPS < 4 )); then
    export LA_DETECTOR_MIN_LOC_OBSERVATIONS=1
  else
    export LA_DETECTOR_MIN_LOC_OBSERVATIONS=4
  fi
else
  export LA_DETECTOR_MIN_LOC_OBSERVATIONS
fi

exec "$SCRIPT_DIR/run_la_pseudo_query_pipeline.sh"
